import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { mockAdministration } from "./administration-fixture.mjs";

test("administration filters users and navigates effective organization access", async ({ page }) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await mockAdministration(page);
  await page.goto("/admin.html#users");
  await expect(page.locator("#user-rows tr")).toHaveCount(5);
  await expect(page.locator("#user-editor")).not.toBeVisible();
  await page.getByPlaceholder("Name or email").fill("LEA.WAGNER");
  await expect(page.locator("#user-rows tr")).toHaveCount(1);
  await page.getByRole("button", { name: "Clear filters" }).click();
  await page.locator('#user-filters select[name="status"]').selectOption("disabled");
  await expect(page.locator("#user-rows tr")).toHaveCount(1);
  await page.locator("#organizations-nav").click();
  await expect(page.locator("#organizations-title")).toBeVisible();
  await page.getByRole("button", { name: "View users with access to Vienna Operations", exact: true }).click();
  await expect(page.locator("#user-rows tr")).toHaveCount(5);
  await expect(page.locator("#organization-filter")).toHaveValue("vienna");
  await page.getByPlaceholder("Name or email").fill("no such user");
  await expect(page.locator("#users-empty")).toBeVisible();
  await page.goBack();
  await expect(page.locator("#organizations-title")).toBeVisible();
  expect(errors).toEqual([]);
});

test("creates local and Entra users with conditional fields and CSRF", async ({ page }) => {
  const { writes } = await mockAdministration(page);
  await page.goto("/admin.html");
  await page.getByRole("button", { name: "+ Add user", exact: true }).click();
  await expect(page.locator("#entra-field")).toBeHidden();
  await page.locator('#user-form input[name="username"]').fill("New operator");
  await page.locator('#user-form input[name="password"]').fill("test-only-password-123");
  await page.getByRole("button", { name: "Create user", exact: true }).click();
  await expect(page.locator("#user-error")).toContainText("Select at least one organization");
  await page.locator('#organization-picker input[value="vienna"]').check();
  await page.locator("#grant-search").fill("Vienna");
  await page.locator("#grant-search").press("Enter");
  expect(writes).toHaveLength(0);
  await page.getByRole("button", { name: "Create user", exact: true }).click();
  await expect(page.locator("#user-editor")).toBeHidden();
  expect(writes[0]).toMatchObject({ csrf: "fixture-csrf", data: { authSource: "local", password: "test-only-password-123", organizationIds: ["vienna"], role: "user", allOrganizations: false } });
  expect(writes[0].data).not.toHaveProperty("externalLogin");
  await page.getByRole("button", { name: "+ Add user", exact: true }).click();
  await page.locator('#user-form select[name="authSource"]').selectOption("entra");
  await expect(page.locator("#password-field")).toBeHidden();
  await page.locator('#user-form input[name="username"]').fill("Microsoft operator");
  await page.locator('#user-form input[name="externalLogin"]').fill("operator@example.com");
  await page.locator('#user-form select[name="role"]').selectOption("admin");
  await expect(page.locator("#organization-grants")).toBeHidden();
  await page.getByRole("button", { name: "Create user", exact: true }).click();
  await expect(page.locator("#user-editor")).toBeHidden();
  expect(writes[1].data).toMatchObject({ authSource: "entra", externalLogin: "operator@example.com", role: "admin", allOrganizations: true, organizationIds: [] });
  expect(writes[1].data).not.toHaveProperty("password");
});

test("edits access, protects bootstrap admin and confirms security actions", async ({ page }) => {
  const { writes } = await mockAdministration(page);
  await page.goto("/admin.html");
  await page.getByRole("button", { name: "View admin", exact: true }).click();
  await expect(page.locator("#save-user")).toBeHidden();
  await expect(page.locator('#user-form select[name="role"]')).toBeDisabled();
  await expect(page.locator("#user-security-actions")).toBeHidden();
  await page.getByRole("button", { name: "Close user editor" }).click();
  await page.getByRole("button", { name: "Manage Max Steiner" }).click();
  await page.locator('#organization-picker input[value="linz"]').uncheck();
  await page.getByRole("button", { name: "Save access", exact: true }).click();
  await expect(page.locator("#user-editor")).toBeHidden();
  expect(writes[0].data).toEqual({ role: "user", allOrganizations: false, organizationIds: ["vienna"], disabled: false });
  await page.getByRole("button", { name: "Manage Max Steiner" }).click();
  page.once("dialog", (dialog) => dialog.dismiss());
  await page.getByRole("button", { name: "Disable account", exact: true }).click();
  expect(writes).toHaveLength(1);
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Disable account", exact: true }).click();
  await expect(page.locator("#user-editor")).toBeHidden();
  expect(writes[1].data.disabled).toBe(true);
  await page.getByRole("button", { name: "Manage Anna Berger" }).click();
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Reset Microsoft link", exact: true }).click();
  await expect(page.locator("#user-editor")).toBeHidden();
  expect(writes[2].data.resetExternalIdentity).toBe(true);
});

test("organization create, rename, protections, member navigation and deletion", async ({ page }) => {
  const { writes } = await mockAdministration(page);
  await page.goto("/admin.html#organizations");
  await page.getByRole("button", { name: "Manage Default", exact: true }).click();
  await expect(page.locator("#save-organization")).toBeHidden();
  await expect(page.locator("#delete-organization")).toBeDisabled();
  await page.getByRole("button", { name: "Close organization editor" }).click();
  await page.getByRole("button", { name: "Manage Vienna Operations", exact: true }).click();
  await expect(page.locator("#delete-organization")).toBeDisabled();
  await page.getByRole("button", { name: "View users with access", exact: true }).click();
  await expect(page.locator("#organization-filter")).toHaveValue("vienna");
  await page.locator("#organizations-nav").click();
  await page.getByRole("button", { name: "+ Add organization", exact: true }).click();
  await page.locator('#organization-form input[name="name"]').fill("New branch");
  await page.getByRole("button", { name: "Create organization", exact: true }).click();
  await expect(page.locator("#organization-editor")).toBeHidden();
  await page.getByRole("button", { name: "Manage New branch", exact: true }).click();
  await page.locator('#organization-form input[name="name"]').fill("New branch renamed");
  await page.getByRole("button", { name: "Save name", exact: true }).click();
  await expect(page.locator("#organization-editor")).toBeHidden();
  await page.getByRole("button", { name: "Manage New branch renamed", exact: true }).click();
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Delete organization", exact: true }).click();
  await expect(page.locator("#organization-editor")).toBeHidden();
  await expect(page.locator("#organization-rows tr")).toHaveCount(5);
  expect(writes.map(({ method }) => method)).toEqual(["POST", "PUT", "DELETE"]);
});

test("failed writes retain the editor and unsaved changes require confirmation", async ({ page }) => {
  await mockAdministration(page, { failWrites: true });
  await page.goto("/admin.html#organizations");
  await page.getByRole("button", { name: "Manage Lab", exact: true }).click();
  await page.locator('#organization-form input[name="name"]').fill("Renamed lab");
  await page.getByRole("button", { name: "Save name", exact: true }).click();
  await expect(page.locator("#organization-error")).toContainText("Organization contains maps");
  await expect(page.locator('#organization-form input[name="name"]')).toHaveValue("Renamed lab");
  page.once("dialog", (dialog) => dialog.dismiss());
  await page.keyboard.press("Escape");
  await expect(page.locator("#organization-editor")).toBeVisible();
  page.once("dialog", (dialog) => dialog.accept());
  await page.keyboard.press("Escape");
  await expect(page.locator("#organization-editor")).toBeHidden();
});

test("non-administrators never load the directory", async ({ page }) => {
  const { requests } = await mockAdministration(page, { role: "user" });
  await page.goto("/admin.html");
  await expect(page.locator("#page-error")).toContainText("Administrator access required");
  await expect(page.locator("#administration-content")).toBeHidden();
  expect(requests.some((path) => path.startsWith("/api/v1/admin/"))).toBe(false);
});

test("load errors recover and successful mutations are not repeated after a refresh error", async ({ page }) => {
  const options = { failReads: true, failRefresh: true };
  const { writes } = await mockAdministration(page, options);
  await page.goto("/admin.html#organizations");
  await expect(page.locator("#page-error")).toContainText("Could not load administration");
  await expect(page.locator("#administration-content")).toBeHidden();
  options.failReads = false;
  await page.getByRole("button", { name: "Try again" }).click();
  await expect(page.locator("#organizations-title")).toBeVisible();
  await page.getByRole("button", { name: "+ Add organization", exact: true }).click();
  await page.locator('#organization-form input[name="name"]').fill("Recovery lab");
  await page.getByRole("button", { name: "Create organization", exact: true }).click();
  await expect(page.locator("#page-error")).toContainText("Change saved, but the directory could not be refreshed");
  await expect(page.locator("#organization-editor")).toBeHidden();
  expect(writes).toHaveLength(1);
  options.failRefresh = false;
  await page.getByRole("button", { name: "Try again" }).click();
  await expect(page.getByRole("button", { name: "Manage Recovery lab", exact: true })).toBeVisible();
  expect(writes).toHaveLength(1);
  await page.locator(".skip-link").focus();
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(/#organizations$/);
  await expect(page.locator("#main")).toBeFocused();
});

test("desktop and mobile administration are accessible and contain scrolling", async ({ page }, testInfo) => {
  await mockAdministration(page);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/admin.html");
  await expect(page.locator("#user-rows tr")).toHaveCount(5);
  let audit = await new AxeBuilder({ page }).analyze();
  expect(audit.violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("administration-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("administration-mobile.png"), fullPage: true });
  await page.getByRole("button", { name: "+ Add user", exact: true }).click();
  audit = await new AxeBuilder({ page }).analyze();
  expect(audit.violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("administration-editor.png"), fullPage: true });
  await expect(page.locator("#save-user")).toBeInViewport();
});
