import test from 'node:test';
import assert from 'node:assert/strict';
import {eatonAdditionProfiles,eatonAdditionConfigurations} from './static/js/catalog-eaton-additions.js';
import {instantiateProfile,hardwareCatalog,upgradeInstalledPhysicalPorts} from './static/js/catalog.js';
import {resolveEatonAdditionFaceplate} from './static/js/faceplate-eaton-additions-models.js';
import {resolveModelFaceplate} from './static/js/faceplate-models.js';
import {buildFaceplateScene} from './static/js/faceplate-scene.js';
import {hardwarePrimitives} from './static/js/hardware-components.js';
/** Create a user-owned saved record with independent IDs and rack placement. */
function deviceFor(c){const d=instantiateProfile(c,'User UPS',{x:47,y:81});d.id='saved-ups';d.rackId='rack-id';d.rackPosition=11;for(const p of d.ports){p.id=`port-${p.portIndex}`;p.deviceId=d.id;}return d;}
/** Detect positive-area intersections, allowing mere edge contact. */
function overlaps(a,b){return a.x<b.x+b.width-1e-6&&a.x+a.width>b.x+1e-6&&a.y<b.y+b.height-1e-6&&a.y+a.height>b.y+1e-6;}
/** Verify full enclosure by a source body or socket housing. */
function contains(a,b){return b.x>=a.x-.001&&b.y>=a.y-.001&&b.x+b.width<=a.x+a.width+.001&&b.y+b.height<=a.y+a.height+.001;}
/** Calculate bounds for every actual primitive, including conservative text estimates. */
function points(p){if(p.kind==='rect')return [[p.x,p.y],[p.x+p.width,p.y+p.height]];if(p.kind==='circle')return [[p.cx-p.r,p.cy-p.r],[p.cx+p.r,p.cy+p.r]];if(p.kind==='polygon')return p.points;if(p.kind==='line')return [[p.x1,p.y1],[p.x2,p.y2]];if(p.kind==='text'){const w=p.text.length*p.fontSize*.62;return [[p.x-w/2,p.y-p.fontSize/2],[p.x+w/2,p.y+p.fontSize/2]];}return [];}
for(const c of eatonAdditionProfiles){const cfg=eatonAdditionConfigurations.get(c.model);
 test(`${c.model} integrates the exact original outlet, battery and cooling population`,()=>{
  const row=hardwareCatalog.find(p=>p.vendor===c.vendor&&p.model===c.model);assert.ok(row);const d=deviceFor(row),p=resolveEatonAdditionFaceplate(d);assert.equal(resolveModelFaceplate(d),p);assert.deepEqual(d.ports.map(p=>[p.portIndex,p.label,p.type]),cfg.labels.map((label,i)=>[i+1,label,'Power']));assert.ok(d.ports.every(p=>p.speedMbps===0&&!p.isPoe));assert.equal(d.faceplate.inventoryRevision,1);assert.equal(p.faces.front.ports.length,0);assert.equal(p.faces.rear.ports.length,cfg.labels.length);assert.equal(p.sku,cfg.sku);const scene=buildFaceplateScene(d,{x:0,y:0,width:690,height:c.units*100},{face:'rear'});assert.ok(scene.ports.every(p=>p.connectorKind.startsWith('eaton-addition-')));assert.ok(scene.ports.every(p=>hardwarePrimitives({...p,kind:p.connectorKind}).every(a=>a.kind!=='text')));assert.deepEqual(p.evidence.models,[c.model]);assert.equal(p.faces.rear.components.filter(p=>p.kind==='fan').length,cfg.key==='5px'?2:cfg.key==='9px'?1:0);assert.equal(p.faces.front.components.filter(p=>p.variant==='eaton-addition-display').length,cfg.key==='ebm'?0:1);assert.ok(Object.values(p.faces).every(f=>f.components.every(p=>p.active===false)));assert.equal(p.faces.rear.ports.filter(p=>p.connectorKind.includes('c13')).length,cfg.key==='ebm'?0:8);assert.equal(p.faces.rear.ports.filter(p=>p.connectorKind.includes('-c19')).length,cfg.key==='5px'?1:cfg.key==='9px'?2:0);
 });
 test(`${c.model} preserves full edited saved records and never guesses old or incompatible endpoints`,()=>{
  const d=deviceFor(c);d.ports.reverse();for(const p of d.ports)Object.assign(p,{label:`edited ${p.portIndex}`,speedMbps:123,mode:'Trunk',nativeVlan:41,allowedVlans:[41,93],isPoe:true,group:'custom'});
  const state={devices:[d],links:d.ports.map(p=>({id:`cable-${p.id}`,fromDeviceId:d.id,fromPortId:p.id,toDeviceId:'remote',toPortId:`other-${p.id}`,color:'#aabbcc',points:[{x:3,y:19}]}))},before=structuredClone(state);assert.equal(upgradeInstalledPhysicalPorts(state),false);const s=buildFaceplateScene(d,{x:0,y:0,width:690,height:c.units*100},{face:'rear'});assert.equal(s.ports.length,cfg.labels.length);assert.deepEqual(state,before);assert.ok(s.ports.every(p=>p.displayLabel.startsWith('edited')));
  d.ports=d.ports.filter(p=>p.portIndex<=2);d.ports.find(p=>p.portIndex===2).type='RJ45_1G';const sparse=buildFaceplateScene(d,{x:0,y:0,width:460,height:c.units*100},{face:'rear'});assert.deepEqual(sparse.ports.map(p=>p.port.portIndex),[1]);assert.equal(sparse.unmappedPorts.length,1);assert.equal(sparse.components.filter(p=>p.ancillarySocket).length,cfg.labels.length-1);
  for(const rev of [undefined,0,99,-1,1.5,'1']){if(rev===undefined)delete d.faceplate.inventoryRevision;else d.faceplate.inventoryRevision=rev;const prior=structuredClone(d),scene=buildFaceplateScene(d,{x:0,y:0,width:690,height:c.units*100},{face:'rear'});assert.equal(scene.ports.length,0);assert.equal(scene.unmappedPorts.length,2);assert.equal(scene.components.filter(p=>p.ancillarySocket).length,cfg.labels.length);assert.deepEqual(d,prior);}
 });
 test(`${c.model} respects physical dimensions, caption clearance and ancillary socket positions`,()=>{
  for(const width of [460,690])for(const units of [1,c.units,4])for(const sparse of [false,true])for(const face of ['front','rear']){const d=deviceFor(c);d.faceplate.unitsU=units;if(sparse)d.ports=d.ports.filter(p=>p.portIndex%2===1);const s=buildFaceplateScene(d,{x:0,y:0,width,height:units*100},{face}),scale=Math.min(1,units/c.units),physical=[...s.ports,...s.components.filter(p=>!p.applicationOverlay)];assert.equal(s.chassis.componentDrawn,true);assert.ok(Math.abs(s.chassis.height-690*cfg.height/482.6*scale)<1e-7);assert.ok(Math.abs(s.chassis.width-width*cfg.width/482.6*scale)<1e-7);
   for(const p of physical)assert.ok(contains(s.chassis,p),`${p.role||p.displayLabel} bounds`);
   for(const p of s.ports){for(const q of physical)if(q!==p&&!(q.hardwareLayer==='chassis-container'&&contains(q,p)))assert.ok(!overlaps(p,q),`${p.displayLabel} overlaps ${q.role||q.displayLabel} at${width}/${units}`);const a=p.labelPlacement;if(a.hidden)continue;const w=Math.min(a.boxMaxWidth,Math.max(12,Math.min(a.maxWidth,p.displayLabel.length*a.fontSize)+6)),label={x:a.x-w/2,y:a.y-a.boxHeight/2,width:w,height:a.boxHeight};assert.ok(contains(s.chassis,label),'caption bounds');for(const q of physical)if(q.role!=='body')assert.ok(!overlaps(label,q),`caption${p.displayLabel} overlaps${q.role||q.displayLabel}`);}
   if(sparse){const fresh=deviceFor(c);fresh.faceplate.unitsU=units;const t=buildFaceplateScene(fresh,{x:0,y:0,width,height:units*100},{face});for(const q of s.components.filter(p=>p.ancillarySocket)){const current=t.ports.find(p=>p.port.portIndex===q.physicalSlotIndex);assert.ok(current);for(const key of ['x','y','width','height'])assert.equal(q[key],current[key]);}}
  }
 });
 test(`${c.model} keeps every real artwork primitive bounded at new and saved sizes`,()=>{
  for(const width of [460,690])for(const units of [1,c.units,4])for(const empty of [false,true])for(const face of ['front','rear']){const d=deviceFor(c);d.faceplate.unitsU=units;if(empty)d.ports=[];const s=buildFaceplateScene(d,{x:0,y:0,width,height:units*100},{face});for(const component of [...s.components.filter(p=>!p.applicationOverlay),...s.ports.map(p=>({...p,kind:p.connectorKind}))]){const primitives=hardwarePrimitives(component);assert.ok(primitives.length,`${component.variant} artwork`);for(const p of primitives)for(const [x,y]of points(p))assert.ok(x>=component.x-.001&&x<=component.x+component.width+.001&&y>=component.y-.001&&y<=component.y+component.height+.001,`${component.role||component.displayLabel} ${p.kind} primitive at${width}/${units}`);}}
 });
}
test('Eaton addition dispatch rejects unknown names, prototype keys, vendor and category mismatches',()=>{
 for(const model of ['constructor','toString','__proto__','9PX5000IRT','9PXEBM180RT3UG2','5PX3000IRT2UG2']){const d={category:'Server',model,faceplate:{vendor:'Eaton',unitsU:3},ports:[]};assert.equal(resolveEatonAdditionFaceplate(d),null);assert.equal(resolveModelFaceplate(d),null);}const d=deviceFor(eatonAdditionProfiles[0]);d.faceplate.vendor='APC';assert.equal(resolveEatonAdditionFaceplate(d),null);d.faceplate.vendor='Eaton';d.category='Switch';assert.equal(resolveEatonAdditionFaceplate(d),null);
});

/** Confirm source-facing polarization: on the5PX rear, the single earth contact is right of the two line contacts. */
test('Original5PX portrait IEC artwork follows manufacturer connector orientation',()=>{const d=deviceFor(eatonAdditionProfiles.find(c=>c.sku==='5PX3000IRT2U'));const scene=buildFaceplateScene(d,{x:0,y:0,width:690,height:200},{face:'rear'});for(const index of [1,10]){const p=scene.ports.find(p=>p.port.portIndex===index),fill=index===10?'#c4cdd0':'#03090d',pins=hardwarePrimitives({...p,kind:p.connectorKind}).filter(a=>a.kind==='rect'&&a.fill===fill);assert.equal(pins.length,3);assert.ok(pins[1].x>pins[0].x);assert.ok(pins[1].x>pins[2].x);}});

/** The original9PX manual shows earth below the line/neutral pair on both C13 and C19 outputs. */
test('Original9PX output polarization follows its inverted factory mounting',()=>{const d=deviceFor(eatonAdditionProfiles.find(c=>c.sku==='9PX5KiRT'));const scene=buildFaceplateScene(d,{x:0,y:0,width:690,height:300},{face:'rear'});for(const index of [1,9]){const p=scene.ports.find(p=>p.port.portIndex===index),pins=hardwarePrimitives({...p,kind:p.connectorKind}).filter(a=>a.kind==='rect'&&a.fill==='#03090d');assert.equal(pins.length,3);assert.ok(pins[1].y>pins[0].y);assert.ok(pins[1].y>pins[2].y);}});
